greeting:
  message: "hello"
quarkus:
  hibernate-orm:
    database:
      generation: "none"
  datasource:
    db-kind: mysql
    username: root
    password: ${db_pass}
    jdbc:
      url: jdbc:mysql://localhost:3306/studen_db
      max-size: 16
  http:
    port: 8087

mp:
  jwt:
    verify:
      issuer: Ayush
    publickey:
      location: keys/publicKey.pem
